<?php

function tov_event_node_view_alter(&$build) {

  //hide the event arrival flag if approval period is not now:
  if($build['#entity_type'] == 'node' && $build['#bundle'] == 'event') {
	  if(!($build['#node']->field_date_approval_period['und'][0]['value'] < time() && time() < $build['#node']->field_date_approval_period['und'][0]['value2'])) {
		  unset($build['flag_arrive_event_node_flag']);
	  }
  }
}
