<?php
 

function bruria_commerce_price_formatted_components_alter(&$components, $price, $entity) {
  foreach ($components as &$component) {
    $component['title'] = t($component['title']);
  }
}

function bruria_form_alter(&$form, &$form_state, $form_id) { 
  if (strpos($form_id, 'commerce_cart_add_to_cart_form') !== FALSE) {
    if ($form['submit']['#value'] == t('Add to cart')){
      $form['submit']['#value'] = t('Register');
    }
    else{
      $form['submit']['#value'] = t('Registration closed');
    }
  }
}

function bruria_form_comment_form_alter(&$form) {
  $form['author']['homepage']['#access'] = FALSE;
}

 function bruria_views_access_callbacks() {
  return array(
    'bruria_user_has_access' => t('User can only see tab on his own profile'));
}

function bruria_user_has_access() {
  global $user;
  if (arg(0) == 'user' && $user->uid == arg(1)){
    return TRUE;
  }
  else {
    return FALSE;
  }
}


?>
